### ISSUE TITLE
多家医院单队列/多队列联合，同步分析

### ISSUE THREAD

**Issue by leizhaojin** [hebta/bugtrack#12]
1. 多个中心（医院），无论是单队列还是多队列分析，都需要各自完成本地的相同分析，分析结果可以共享。
2. 在各自分析完成并且成功后，请求方才可以选择“合并分析”，将多家医院的Matrix实时共享再做相同分析，其结果保存在请求方

**Comment by leizhaojin** [comment]
我在本地和小秦的机器上测试过了，前端再double check 一下

**Comment by Jasondiao** [comment]
FYI: TESTING
@leizhaojin @QinChenHuan Follow and Fix
@hbt-lgb @houanran @wwwxq Jason  Test and Fix

**Comment by leizhaojin** [comment]
李国兵和我已经完成一轮测试，前后端代码包都交给实施，部署多中心
