### ISSUE TITLE
Curie测试 bug

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#15]
分析结果没出来，待修复

**Comment by hbtlichao** [comment]
09:29:29 WARN  [com.hebta.curie.service.StatisticalService] - T-Test 耗时 1 秒
09:29:29 INFO  [com.hebta.curie.service.StatisticalService] - 进入置信区间计算方法 calcConfInt()
09:29:29 INFO  [com.hebta.curie.service.BaseStatService] - 变量 AGE 是定量变量，得用 double[] 作为接收类型
09:29:29 INFO  [com.hebta.curie.service.BaseStatService] - 变量 AGE 是定量变量，得用 double[] 作为接收类型
09:29:29 ERROR [com.hebta.curie.service.StatisticalService] - StatisticalService:calcConfInt, cohort name:Abdominal_Matched_Control_Control, variable name:AGE, error message:R command failed with error. Reason: Error: package ‘DescTools’ was built for x86_64-w64-mingw32
In addition: Warning message:
package ‘DescTools’ was built under R version 3.4.1 
Execution halted

09:29:29 ERROR [com.hebta.curie.service.StatisticalService] - StatisticalService:calcConfInt, cohort name:Laparoscopic_Matched_Case_Case, variable name:AGE, error message:R command failed with error. Reason: Error: package ‘DescTools’ was built for x86_64-w64-mingw32
In addition: Warning message:
package ‘DescTools’ was built under R version 3.4.1 
Execution halted

09:29:29 WARN  [com.hebta.curie.service.StatisticalService] - Confidence Interval 计算耗时 0 秒
09:29:29 INFO  [com.hebta.curie.service.StatisticalService] - Statistics统计完成，将结果保存到数据库
09:29:31 INFO  [com.hebta.curie.controller.StatisticalController] - 进入获取 Statistics 页签的分析结果 getStatisticsView()
09:29:31 INFO  [com.hebta.curie.service.StatisticalService] - 参数analysisDefinitionId：381, type:statistics
09:29:37 INFO  [com.hebta.curie.controller.StatisticalController] - 进入获取 Statistics 页签的分析结果 getStatisticsView()

**Comment by leizhaojin** [comment]
试试在Linux上安装 R 的 DescTools，或者功能类似的包
