### ISSUE TITLE
Curie测试BUG

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#16]
- [x] 1. 相同的筛选条件通过cohort line 和cohort筛选的样本量不同（至少要达到两个筛选条件时一致）
- [x] 2. PDC,MPR这两个指标是百分率，原始数值和最终的均数结果不太一致，quantity这个指标原始有数值，但最终结果算不出来。
- [x] 3. Table分析proportion比例计算有问题
- [ ] 4. 涉及到allowed gap 概念的时间比较久
- [ ] 5. 涉及到number of treated days的时间比较久
- [x] 6. T检验和方差分析的结果没有保留三位小数
- [x] 7. table有一组年龄的均值和标准差计算不出来
- [x] 8. T检验修改默认项为independent samples
- [x] 9. 匹配replacement去掉
- [ ] 10. 匹配失败
- [x] 11. 新建队列时可将次要条件与主要条件的关系次序处将概念集合设为at least
- [x] 12. T检验和方差分析的P和F以及自由度计算不对

1. 实现concurrent treatment时需要得到患者同时服用选定药物的天数（在变量中添加at the same time），能够得出最长最短天数（longest gap）
2. 实现continuous treatment和discontinuation，需判定一个患者是否是持续治疗，得到一个分类变量，用于后续统计持续治疗的百分比
3. 实现MPR，需要得到每个患者在观察期内服药天数所占的比例（gap算在分子的）
4. 实现PDC，与MPR类似，分子不考虑gap的天数，服用药物的种类和剂量不管

**Comment by Jasondiao** [comment]
有问题及时补充

**Comment by leizhaojin** [comment]
Test

 

--------------------------------------------------------

Allen Lei

+86-15051509015

苏州工业园区星湖街328号创意产业园2-A301室

 

发件人: bounces+848413-b89d-lallen=hebtahealth.com.cn@sgmail.github.com [mailto:bounces+848413-b89d-lallen=hebtahealth.com.cn@sgmail.github.com] 代表 Jason.diao
发送时间: 2017年12月29日 14:45
收件人: hebta/bugtrack <bugtrack@noreply.github.com>
抄送: leizhaojin <lallen@hebtahealth.com.cn>; Assign <assign@noreply.github.com>
主题: Re: [hebta/bugtrack] Curie测试BUG (#16)

 

Assigned #16 <https://github.com/hebta/bugtrack/issues/16>  to @leizhaojin <https://github.com/leizhaojin> .

**Comment by QinChenHuan** [comment]
第4点，第5点时间比较久的问题暂时没有很好的方案调整，因为必须要去跑数据库中所有人的用药周期。这个先记下，再想想有没有什么好的方案。

**Comment by QinChenHuan** [comment]
$1.两种情况是不同的逻辑。比如说有人10-31诊断为糖尿病，10-27和11-23服用二甲双胍。这样在COHORT_LINE中会去取二甲双胍的入队列时间（10-27）和糖尿病的入队列时间（10-31）比，发现二甲双胍的时间晚，所以不被纳入，COHORT_LINE的队列。但是要是把二甲双胍放入糖尿病队列的次要条件，那么二甲双胍的两次时间都会去和糖尿病的入队列时间比教，发现二甲双胍的11-23发生在糖尿病入队列之后，所以该病人会被纳入队列。

**Comment by leizhaojin** [comment]
$7. table有一组年龄的均值和标准差计算不出来
有些队列的年龄的值计算没有问题，说明程序没问题，至于bug提出时看到的 NA 很有可能是数据问题，比如脏数据没有剔除，这个需要重现，来确定这个猜测，目前算没问题
$12. T检验和方差分析的P和F以及自由度计算不对
在 方差相等 的前提下，自由度是整数。只在 方差不相等 的前提下，自由度才显示带有小数。也可以认为没问题了。
