### ISSUE TITLE
Vinci测试BUG

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#17]
- [x] 1. 项目无法删除
- [x] 2. 导出matrix表头乱码
- [x] 3. Matrix导出失败，怀疑调用Matrix合并接口时把原来的Matrix删掉了
- [x] 4. 自定义临床路径第一层有费用，第二层没有费用，第三层没有人不管条件如何
- [x] 5. t检验问题：匹配过后长度还是不一致，不能用配对t
- [x] 6. 回归模型里，变量名称显示有问题
- [x] 7. 生成matrix，按钮点击完好几秒才有反应，体验感不好，总以为点击的没有作用
- [x] 8. matrix生成第一次可以出来，后面在点一次，或者换一个队列，就出不来了，或者一直显示的是一个，没有变化
- [x] 9. 状态是生成中，点击预览是大片红色代码
- [x] 10. 任一集合有问题，选择任一集合，一直在生成中出不来队列
- [x] 11. 样本预测，检索后样本量为0
 #######################################################
 多中心
 #######################################################
- [x] 12. 取其他医院的分析结果出错
- [x] 13. 合并分析结果没有获取，但是第一人民医院的结果是有的
- [x] 14. 导出CSV乱码
- [x] 15. 两个组做病例的匹配都失败
- [x] 16. cox没有结果，不知道是不是变量的原因
- [x] 17 .同样有模型里变量名称显示的问题
- [x] 18. 这导出和人员变更的申请没有登录centre的账号审批，为什么还出现审核状态？
- [x] 19. 队列统计失败
- [x] 20. 运营统计，还是那3个图有问题
- [x] 21. 样本预测没有人，同样的条件，高级检索有人
- [x] 22. 预测模型，值和曲线都是完全一样的
- [x] 23. 预测模型导出，数据都在一列
- [x] 24. 样本预测检查人数看不到其他医院的预测量

**Comment by Jasondiao** [comment]
有问题及时补充

**Comment by hbt-lgb** [comment]
6. 回归模型 
分析需要部分变量无法设置中文名

**Comment by leizhaojin** [comment]
5. t检验问题：
让实施拿到后台的 R 程序和相关日志（最好有日志帮助分析），然后我看看哪里出问题了。

**Comment by hbt-lgb** [comment]
7. 优化生成matrix点击体验
8. 多中心新版本无此bug
已修复

**Comment by leizhaojin** [comment]
$5. t检验问题：匹配过后长度还是不一致，不能用配对t
根据我在JSDEMO数据库上的ANALYSE_DEFINITION_ID = 1132测试，匹配后无论是独立样本还是配对样本都可以完成 T 检验
$6. 回归模型里，变量名称显示有问题
这是由于测试基于队列的，程序使用了 group 变量，而前端是根据 note 属性显示名称的，所以页面上显示空白
$15.  两个组做病例的匹配都失败
这个的确是个 bug, SVN 代码提交号：464.
$16.  cox没有结果，不知道是不是变量的原因
我的ANALYSE_DEFINITION_ID = 1132测试显示 COX 分析没问题，需要再次测试确认下是否真的是变量问题
$17 .同样有模型里变量名称显示的问题
这个和第 6 题同出一辙

**Comment by hbt-lgb** [comment]
$6. $17. 变量group拆分成队列显示，变量名intercept显示为截距。
已修复

**Comment by QinChenHuan** [comment]
$19是数据库权限问题，跑队列统计的时候会创建和删除临时表，所以数据库用户必须要有创建和删除表的权限

**Comment by leizhaojin** [comment]
$3. Matrix导出失败，怀疑调用Matrix合并接口时把原来的Matrix删掉了
走查代码，并没有发现什么地方会删除硬盘上的文件，这个问题如果是个bug，需要重现下并记录重新步骤

**Comment by QinChenHuan** [comment]
$10在人数多的那个数据库中，有100多万人，生成队列需要很长时间

**Comment by leizhaojin** [comment]
$ 12. 取其他医院的分析结果出错
是一个bug，同步数据插入 Project 的时候判断 ID 出错，导致程序中断。 SVN 代码提交号：470

**Comment by leizhaojin** [comment]
$13. 合并分析结果没有获取，但是第一人民医院的结果是有的
合并分析出错，是因为合并分析直接取导出的Matrix数据，而导出的Matrix 的Key 是变量的 note，方便阅读。但是程序是根据 varName取值, 所以 Matrix 加载到内存需要处理 note/varName 的问题。待修复。

**Comment by leizhaojin** [comment]
$13. 合并分析结果没有获取，但是第一人民医院的结果是有的
问题已解决，代码提交SVN号：471
