### ISSUE TITLE
EDC测试bug

### ISSUE THREAD

**Issue by wwwxq** [hebta/bugtrack#18]
- [x] 1.多项填空放一行不好填
- [x] 2. 知情同意书、结束语的内容不能改动
- [x] 3.问卷导出，未知错误
- [x] 4.线上问卷的研究者，应该是账号本人，填写日期是当天，最好是用户提交后自动填写
- [x] 5.复制过来的名称，发布后的显示有问题

**Comment by hbt-lgb** [comment]
$1. $2 $3 $5 已修复
$4 修改为 线上问卷制作时，研究者为必填项。用户提交答卷后，日期自动填写。
