### ISSUE TITLE
Curie扩展开发

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#20]
- [x] Variable Line
- [x] T检验类型paired
- [x] 广义线性回归Family中Gaussian、Gamma、Inverse.gaussian、Quasi、Quasibinomial、Quasipoisson
- [x] 广义线性回归模型里面的排序

**Comment by leizhaojin** [comment]
$ T检验类型paired
独立开一个接口，（前端调用）判断是否可以选择配对样本测试 Committed revision 198

**Comment by leizhaojin** [comment]
$  广义线性回归模型里面的排序
功能已添加，Committed revision 200

**Comment by leizhaojin** [comment]
$ 广义线性回归Family中Gaussian、Gamma、Inverse.gaussian、Quasi、Quasibinomial、Quasipoisson
比较 SPSS 和 R，共同的 Model 和 link function 如下：
binomial |  
  | log
  | logit
  | probit
  | cloglog
gaussian |  
  | identity
  | log
Gamma |  
  | identity
  | log
inverse.gaussian |  
  | identity
  | log
poisson |  
  | identity
  | log
其他的不敢贸然加上。后台的代码已完成，也是 Committed revision 200 提交的。

**Comment by Jasondiao** [comment]
@wwwxq 和SPSS对比一下，测试验证下准确性

**Comment by hbt-lgb** [comment]
$ Variable Line
  页面制作完成

**Comment by Jasondiao** [comment]
ready to test

**Comment by Jasondiao** [comment]
redirect to #22
