### ISSUE TITLE
curie bug

### ISSUE THREAD

**Issue by wwwxq** [hebta/bugtrack#22]
curie GLM 中的5个模型结果与spss结果不一致分别如下
- [x] binomial
- [x] gaussian
- [x] gamma
- [x] inverse gaussian
- [x] poisson

**Comment by leizhaojin** [comment]
比对 SPSS 和 R 的分析结果，Gamma/Inverse Gaussian/Poisson 数值一致，Gaussian的系数相同，但是P值不同。Binomial 的 first/last 排序和以往的理解不同，需要反转下，值才能一致。代码已提交，等待部署测试。

**Comment by Jasondiao** [comment]
binomial 和 poisson 一致。
gaussian、gamma、inverse gaussian还是不一致，请加快时间，有问题抛出来。

**Comment by leizhaojin** [comment]
正在咨询上海的大咖。。。。

**Comment by Jasondiao** [comment]
Okay, 这些分析很重要也很紧急，希望相关人员能够重视起来。

**Comment by leizhaojin** [comment]
上海的曹智杰说这个很可能是两个软件在 P 值上的计算不一致，具体怎样，他也不清楚。
正在问Lanting Li， 她说这两天会给我答复，也催了，但是还没回复，正在等。。。

**Comment by leizhaojin** [comment]
目前修改了 SPSS的一些默认配置，发现在一个具体测试样本上，分析结果的数字和R程序的非常接近了。下周一再用其他测试样本验证，如果没问题，需要在我们的Models分析页面上注明这个情况。也就是 R 程序本身不需要修改，只是 R 的默认配置和 SPSS 的不一样。

**Comment by leizhaojin** [comment]
经过几个不错的样本测试，在 SPSS 做部分设置修改的情况下，两边的分析结果非常接近，证明了 R 的分析没问题，代码无需修改。问题已找到，只需要再在服务器上跑，比对下分析结果。

**Comment by leizhaojin** [comment]
Estimation Tab -> Scale Parameter Method -> Pearson chi-square
Statistics -> Chi-Square Statistics -> Likelihood Ratio

**Comment by wwwxq** [comment]
经过测试，在修改SPSS（上述）配置的情况下，CURIE的 R 的分析结果和SPSS 一致。
