### ISSUE TITLE
Learning Effective Clinical Treatment Pathways from Data

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#24]
http://www.ohdsi.org/web/wiki/doku.php?id=research:learning_effective_clinical_treatment_pathways_from_data

重现该研究

**Comment by leizhaojin** [comment]
直接调用该开源代码出现问题，已写好文档发给王强，寻求永辉，璟琦的帮助

**Comment by Jasondiao** [comment]
待美国团队回复，正在催

**Comment by leizhaojin** [comment]
目前 SQL 的问题已解决，但是新的问题又来了，整理问题的文档发给了王强

**Comment by leizhaojin** [comment]
正如璟琦所说，CohortMethod::DataLoadingSaving.R::getDbCohortMethodData这个函数出问题了，我找到具体的行在源文件的 275行，初步判断这个是数据库的数据不满足要求，该SQL文件是： CountOverallExposedPopulation.sql。需要在数据库执行下看返回的数据是怎样的。。。

**Comment by leizhaojin** [comment]
发现 JSDEMO 数据库的 Concept 数据不满足 DiabetesTxPath 开源代码的SQL需求，打算尝试南昌或者省人民数据库。。。。

**Comment by leizhaojin** [comment]
程序要运行，必须建立在OHDSI数据库上，因为DiabetesTxPath里面的sql 语句写死了 concept_id。今天在执行整个分析的时候，RGui 始终定在初始的 sql 语句执行上，不管是我的机器还是小秦的，可能是数据库繁忙。待下班的时候再跑一下。。。

**Comment by leizhaojin** [comment]
李鹏修改部分SQL文件，减少数据的查询量，最终整个程序可以跑通并出结果。R 包和分析的 R 程序都给王强了，已在服务器上跑（时间会很长），等出结果。

**Comment by leizhaojin** [comment]
结果已出，程序可以跑通，可以关闭这个 issue 了

**Comment by Jasondiao** [comment]
R程序完成，后续研究遇到问题再开新的issue.
