### ISSUE TITLE
Vinci优化

### ISSUE THREAD

**Issue by hbt-lgb** [hebta/bugtrack#28]
回归模型
- [x] 1、多项式逻辑回归样式更改
- [x] 2、线性回归样式更改
- [x] 3、广义线性回归和线性回归选参范围修改
- [x] 4、广义线性回归LinkFunction功能添加
- [x] 5、用结局变量替换group
生成Matrix
- [x] 6、matrix变量选择增加全选功能

**Comment by leizhaojin** [comment]
后端代码已提交，包括替换变量和增加参考值属性，committed version: 488

**Comment by hbt-lgb** [comment]
前端代码已提交，问题1、2、3、4完成。
