### ISSUE TITLE
疾病预测模型系统开发

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#29]
- [x] 多条件搜索
- [x] 搜索结果分页
- [x] 病人基本信息
- [x] 就诊信息（住院信息、患者病程、用药信息、手术信息、出院信息）
- [x] 选择模型预测结果（年龄、性别、民族、疾病）
- [ ] 测试

**Comment by Jasondiao** [comment]
- [ ] 多条件搜索
- [ ] 搜索结果分页
- [ ] 病人基本信息
- [ ] 就诊信息（住院信息、患者病程、用药信息、手术信息、出院信息）
- [ ] 选择模型预测结果（年龄、性别、民族、疾病）

**Comment by leizhaojin** [comment]
多条件搜索需要实施新建一个表来保存所有检索字段的数据。后端开发方面：工程已建好，搜索病人信息功能已写完（拷贝完），测试通过，并代码提交到SVN

**Comment by leizhaojin** [comment]
人群的必需信息和预测结果功能也实现，但是目前不知道具体的表面和字段，都是写死在程序里。真正测试的时候需要跟实施沟通好，然后保持一致就好。

**Comment by leizhaojin** [comment]
联调通过，可以关闭了

**Comment by Jasondiao** [comment]
待数据接入测试

**Comment by hbtlichao** [comment]
病人详细信息显示不完全，在总览里面有诊断信息，但点到具体信息时又没有诊断信息
附 病人身份证id为：37030219740807296x

**Comment by hbtlichao** [comment]
病人详细信息显示不完全，在总览里面有诊断信息，但点到具体信息时又没有诊断信息

**Comment by Jasondiao** [comment]
@hbtlichao 输入条件是什么？点击哪个诊断信息，具体信息没有内容的？都记录下来
