### ISSUE TITLE
Vinci新加逻辑回归预测模型 

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#31]
- [x] logistics分析

deadline：--2018.04.11

**Comment by leizhaojin** [comment]
可以先把Curie 的多项式逻辑回归的代码拷贝过来，但是 ROC 图需要点时间，不敢保证 4.11号就能出来

**Comment by leizhaojin** [comment]
王强给了我ROC图的程序，可以参考

**Comment by leizhaojin** [comment]
后端代码实现完成，初步联调通过

**Comment by Jasondiao** [comment]
正在测试

**Comment by hbtlichao** [comment]
Warning message:
In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
  prediction from a rank-deficient fit may be misleading
Waiting for profiling to be done...
Error in coef[3, ] : subscript out of bounds
Execution halted

**Comment by hbtlichao** [comment]
可以把 coef[3,] 去掉  吗

**Comment by Jasondiao** [comment]
测试完成
