### ISSUE TITLE
NC需求4/24

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#34]
1.研究分析结果中的变量统计，如果有空值就会出现NAN
2.卡方检验的结果有问题
3，生成的word论文模板无法打开，
4，cox分析无法使用，一直失败

**Comment by leizhaojin** [comment]
1.研究分析结果中的变量统计，如果有空值就会出现NAN
-- 代码已提交，等待南昌部署新包后，再测试下
2.卡方检验的结果有问题
-- 任元凯说南昌的新包里面没有这个卡方功能了
4，cox分析无法使用，一直失败
-- 问题本质上和 1 相同，都是变量的值在处理过程中有无法转型为数字的项，造成分析失败。同样已修复，但是任元凯说南昌那边Cox分析没有问题了，只能说现在的数据都还不错，修复增加了对边界条件的检查，代码更健壮
