### ISSUE TITLE
Vinci分析方法合并 -- 单队列结果

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#5]
- [x] 结果展示

**Comment by Jasondiao** [comment]
中断，等这周房颤系统结束

**Comment by leizhaojin** [comment]
后台测试通过，联调发现 Anova 和 Confidence Interval 没有通，是因为单队列接口需要前端把当前队列信息放入请求体，保持接口数据结构和多队列的一致即可。

**Comment by Jasondiao** [comment]
Matrix生成貌似还是有点问题

**Comment by leizhaojin** [comment]
问题已经修复,代码提交版本号: 383,384 (多中心版本)

**Comment by Jasondiao** [comment]
FYI：
多家医院联合接入？

**Comment by leizhaojin** [comment]
“多家医院联合接入？” 是多中心联合分析的功能，不属于这个bug

**Comment by leizhaojin** [comment]
新开了 bug 12, 这个如果没问题就可以关了

**Comment by Jasondiao** [comment]
Nice, just fixed.
Pls refer to #12
