### ISSUE TITLE
Vinci分析方法合并 -- 队列比较

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#6]
- [x] 匹配方法
- [x] 分析方法
- [x] 分析结果

**Comment by Jasondiao** [comment]
中断，等这周房颤系统结束

**Comment by leizhaojin** [comment]
后台已经逐个完成分析方法的测试，修复了发现的后端问题，现在多队列的每个分析方法都可以跑通。并把发现的页面问题也反馈给前端开发了，理论上只要前端改好了，单中心项目的多队列分析在跳过匹配的情况下是可以执行任何分析的。

**Comment by leizhaojin** [comment]
新的后台的 vinci 包已发给李超

**Comment by Jasondiao** [comment]
Okay，待开发+测试
匹配方法加入

**Comment by Jasondiao** [comment]
FYI：
匹配方法是否完成？
多家医院联合接入？

**Comment by leizhaojin** [comment]
多中心联合做匹配/分析都已完成，后端完成一轮测试。代码包已交给实施，请前端再double check 一下

**Comment by leizhaojin** [comment]
其实多中心的应该看 bug 12

**Comment by Jasondiao** [comment]
Nice, just fixed.
Pls refer to #12
