### ISSUE TITLE
分析方法合并影响功能

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#7]
- [ ] 队列复制
- [ ] 队列删除
- [ ] 结果预览
- [ ] 结果导出

**Comment by Jasondiao** [comment]
Ticket can be started up. @leizhaojin

**Comment by leizhaojin** [comment]
队列复制，队列删除的后台功能修改完毕。fix version: #351
结果预览和结果导出，小秦会参考 Curie 的模板导出功能

**Comment by Jasondiao** [comment]
FYI: 复制和删除 在方法合并完成后细测。

**Comment by leizhaojin** [comment]
复制应该不会受到影响，删除的逻辑修改了

**Comment by Jasondiao** [comment]
Nice. We will refer to #12 to check.
