### ISSUE TITLE
Matrix导出时间过长

### ISSUE THREAD

**Issue by Jasondiao** [hebta/bugtrack#8]
- [ ] 功能性解决方案

Deadline: 2017-11-06

**Comment by Jasondiao** [comment]
尽可能从功能性角度解决这个问题，虽然有状态控制方案，但是毕竟不是最佳，能不用尽量不要用。

**Comment by leizhaojin** [comment]
如果用户就是希望一次性导出所有变量的Matrix，那么 java 层面只能通过多线程来加快下，时间理论上会减少。但是如果某个变量的计算时间很长，则效果不明显。

**Comment by r64730** [comment]
同意引入多线程方法，单个变量处理时间过长，暂时不考虑

**Comment by Jasondiao** [comment]
Java7 有一个框架叫：Fork/Join，可以将任务拆分成多个子任务，最后得到大任务结果。
可以考虑引入。原理还是多线程。

**Comment by leizhaojin** [comment]
Solution Code Submitted & Local Test Passed: code version #347, 348 (多中心版上提交)

**Comment by Jasondiao** [comment]
Ready to test.

**Comment by Jasondiao** [comment]
这个功能实现方式有所改变，在之后版本里速度可能还是有点慢，但是不会存在Session过期的问题。
